# Session 3

## Task 1

### Write a function to compute 5/0 and use try/except to catch the exceptions.

#### 1

In [7]:
def calculate():
    try:
        5/0
    except ZeroDivisionError:
        print("Division by zero not allowed")

calculate()

Division by zero not allowed


### Implement a Python program to generate all sentences where subject is in

["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"] <br>
verbs=["play","watch"]<br>
objects=["Baseball","Cricket"]


#### Output should come as below:

Americans play Baseball.<br>
Americans play Cricket.<br>
Americans watch Baseball.<br>
Americans watch Cricket.<br>
Indians play Baseball.<br>
Indians play Cricket.<br>
Indians watch Baseball.<br>
Indians watch Cricket.

#### 2

In [41]:
import numpy as np

subjects = ['Americans','Indians']
verbs = ['play','watch']
objects = ['Baseball','Cricket']

output = np.array([subjects,verbs,objects],dtype=np.str)

print(output[0][0] , output[1][0],output[2][0])
print(output[0][0] , output[1][0],output[2][1])
print(output[0][0] , output[1][1],output[2][0])
print(output[0][0] , output[1][1],output[2][1])

print(output[0][1] , output[1][0],output[2][0])
print(output[0][1] , output[1][0],output[2][1])
print(output[0][1] , output[1][1],output[2][0])
print(output[0][1] , output[1][1],output[2][1])

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2

#### 1

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.


In [54]:
x = np.array([1, 2, 3, 5])
N = 4
matrix = np.column_stack([x**(N-1-i) for i in range(N)])
print('Alexandre- Theophile Vandermonde. \n\n', matrix)

Alexandre- Theophile Vandermonde. 

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
